// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnsjvtkumnxzpjbyceos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuc2p2dGt1bW54enBqYnljZW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzQ5NTksImV4cCI6MjA2MzMxMDk1OX0.LSnLt19Fh5bjABQy6prnwBF9KeB6hVb5-AnBu-9RwT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);